//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comm
    {
        public int pkID { get; set; }
        public string Name { get; set; }
        public string Valuee { get; set; }
        public string Typee { get; set; }
    }
}
