//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace b_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        public int pkID { get; set; }
        public int fkUserID { get; set; }
        public int number { get; set; }
        public long price { get; set; }
        public string time { get; set; }
        public string dis { get; set; }
        public Nullable<bool> send { get; set; }
        public string transid { get; set; }
        public string trackingid { get; set; }
        public int factornumber { get; set; }
        public bool pay { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
    }
}
