//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace b_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Owner
    {
        public int pkID { get; set; }
        public string usename { get; set; }
        public string password { get; set; }
        public string GatewaySend { get; set; }
        public string GatewayResult { get; set; }
        public string pin { get; set; }
        public string callback { get; set; }
    }
}
